### PR TITLE
feat: Mobile API v4 from Redwood and `master` into `palm.nelp`

### PR DESCRIPTION
**Pull request by OmarIthawi**
Bring Mobile API v4 from Redwood and `master` into `palm.nelp`.

### List of commits
List of commits on `openedx/edx-platform:master` compared to `open-release/plam.nelp`:

```
edx-platform $ git hist --oneline ...upstream/master -- lms/djangoapps/mobile_api/ 
```

The following the cherry-picked from `master`:

 - [x] 53174178f3 feat: [FC-0047] Extend mobile API with course progress and primary courses on dashboard view (#34848)
     - This is the most important commit, which brings API v4. Everything else is to ensure we don't have conflicts.
 - [x] fca51419f8 refactor: Increase size for mobile config singelton value (#34288)
 - [x] e3851ab3d1 test: Update to reuse variables in more places.
 - [x] 64e91d4080 test: Update to an even longer password.
 - [x] 1e2ea85372 test: Update more tests that had short passwords.
 - [x] 7ae64a5eb4 refactor: Add logging to mobile_api app (#33064)
 - [x] 9fd913bb03 fix: Add platform name to mobile config cache key (#32504)
 - [x] c452fb3204 refactor: rename descriptor -> block within lms/djangoapps/mobile_api

### CODE REVIEW

**Comment by OmarIthawi** [comment]
@johanseto @andrey-canon Tested on devstack:

<details><summary>Screenshot from devstack</summary>

image

</details>

**Review by johanseto — APPROVED** [review]
Mobile API working in my local env

**Review by shadinaif — APPROVED** [review]
LGTM

**Comment by shadinaif** [comment]
Tests on staging went fine, merging...

**Pull request merged**
