### PR TITLE
feat: Studio menu/button to display Unit's Tags (feature flagged) (#3…

### PR DESCRIPTION
**Pull request by andrey-canon**
## Description

This is a backport of https://github.com/openedx/edx-platform/pull/33563 and basically in the palm version shows the following 

image

After pressing the button 

image

For more details follow the instructions of the original PR

### CODE REVIEW

**Review by johanseto — COMMENTED** [review]
Some considerations:
- I have followed the [instructions](https://github.com/openedx/edx-platform/pull/33563) to import taxonomies.
The [command](https://github.com/open-craft/taxonomy-sample-data) failed to the type of import courses(zip),so  I cherry-pick this commit but I don't know if could be useful.
https://github.com/openedx/edx-platform/pull/34191
- I added the django-flag to taxonomies list and doesn't works me for a good time until  I create only one unit. After that, the other units show me everything tag button.
- **Statics**: I don't know If i need a special command to run the static in studio. I ran them, but the taxonomy widget loads me in the footer and strange.

- Anyway the taxonomy route in course-authoring seems working in the desired behaviour.
Peek 2024-05-08 18-24

**Comment by andrey-canon** [comment]
> Some considerations:
> 
> * I have followed the [instructions](https://github.com/openedx/edx-platform/pull/33563) to import taxonomies.
>   The [command](https://github.com/open-craft/taxonomy-sample-data) failed to the type of import courses(zip),so  I cherry-pick this commit but I don't know if could be useful.
>   [feat: Add support for zip files to course and library import code openedx/edx-platform#34191](https://github.com/openedx/edx-platform/pull/34191)
> * I added the django-flag to taxonomies list and doesn't works me for a good time until  I create only one unit. After that, the other units show me everything tag button.
> * **Statics**: I don't know If i need a special command to run the static in studio. I ran them, but the taxonomy widget loads me in the footer and strange.
>   
> * Anyway the taxonomy route in course-authoring seems working in the desired behaviour.
>   Peek 2024-05-08 18-24
>         
>           [
>             
>           
>               Peek 2024-05-08 18-24
>             ](https://private-user-images.githubusercontent.com/51926076/329081968-b8800e3f-f3e5-4e2a-b73d-48ef1603c071.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMTM3NTksIm5iZiI6MTcxNTIxMzQ1OSwicGF0aCI6Ii81MTkyNjA3Ni8zMjkwODE5NjgtYjg4MDBlM2YtZjNlNS00ZTJhLWI3M2QtNDhlZjE2MDNjMDcxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDAwMTA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNmQ5ZGI3ZDIyYjU0YzEyY2EyMzcyMjI4MGI5M2FlMDFhMmRkYTZlN2U4OGJhNWJjZWIyYmRjYmY3NzU3MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zL9P6UEv_gpz91SrA7OyQIgwdjVbFuFzHEfmlo9t40Y)
>           
>           
>             
>               
>                 
>               
>               
>                 
>                 
>               
>             
>             [
>               
>                 
>               
>             ](https://private-user-images.githubusercontent.com/51926076/329081968-b8800e3f-f3e5-4e2a-b73d-48ef1603c071.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMTM3NTksIm5iZiI6MTcxNTIxMzQ1OSwicGF0aCI6Ii81MTkyNjA3Ni8zMjkwODE5NjgtYjg4MDBlM2YtZjNlNS00ZTJhLWI3M2QtNDhlZjE2MDNjMDcxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDAwMTA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNmQ5ZGI3ZDIyYjU0YzEyY2EyMzcyMjI4MGI5M2FlMDFhMmRkYTZlN2U4OGJhNWJjZWIyYmRjYmY3NzU3MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zL9P6UEv_gpz91SrA7OyQIgwdjVbFuFzHEfmlo9t40Y)
> 
> 

1.  I didn't generate the data because the same taxonomy page has the option to export and import tags, so I can not help you with that 
2. I don't understand the issue you had, could you explain the steps to replicate that ?
3. I just used  basic commando like `openedx-assets webpack --env=prod` and `openedx-assets themes --theme-dirs /openedx/themes/nelp-edx-themes  --themes nelp-edx-them`e

**Review by johanseto — APPROVED** [review]
used the webpack command with --env=prod and works.
=)
Peek 2024-05-10 16-45

I only think this PR need a rebase .

**Review by johanseto — APPROVED** [review]
used the webpack command with --env=prod and works.
=)
Peek 2024-05-10 16-45

I only think this PR need a rebase .

**Pull request merged**
